import { Inter, Roboto } from "next/font/google";
import "./globals.css";
import Footer from "@/components/home/Footer";
import Navbar from "@/components/home/Navbar";


const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "400", "700"],
})

export const metadata = {
  title: "JUSTILES",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={roboto.className}>
        <div>
          <Navbar />
          {children}
          <Footer />
        </div> 
      </body>
    </html>
  );
}
